version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL:-jdbc:postgresql://host.docker.internal:5432/itsec_testing}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
